import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import QueryProvider from "./components/QueryProvider";
export const metadata: Metadata = {
  title: "Nextjs Example App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pt-16 pb-20">
        <QueryProvider>
          <Header />
          <main>{children}</main>
          {/* <Footer /> */}
        </QueryProvider>
      </body>
    </html>
  );
}
